# Generated by Django 2.2.24 on 2021-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageaction',
            name='video_call',
            field=models.ManyToManyField(blank=True, related_name='messageaction_video_call', to='chat.ForwardedMessage'),
        ),
    ]
