# Generated by Django 2.2.24 on 2021-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
